export const baseClassNames = [
  'p-1',
  'rounded',
  'text-zinc-300',
  'font-thin',
  'w-32',
  'bg-zinc-800',
  'border-[1px]',
  'overflow-hidden',
  'overflow-visible',
  'border-zinc-700',
  'transition-all',
  'transition-duration-1000',
  'outline',
  'outline-orange-900',
]
