/**
 * Array of class names to be applied to all handles.
 */
export const classNames = [
  'absolute',
  'p-0',
  'signal-handle',
  'border-none',
  '!min-w-0',
  '!min-h-0',
  'border-0',
  'bg-zinc-700',
  'rounded',
  'shadow-[inset_0.2px_0.7px_1px_-0.6px_#ffffff4f]',
]

/**
 * Array of corner names.
 */
export const corners = ['topLeft', 'topRight', 'bottomRight', 'bottomLeft']

/**
 * Mapping of corners to their possible handle types.
 */
const cornerHandleTypes = {
  topLeft: ['top', 'left'],
  topRight: ['top', 'right'],
  bottomRight: ['bottom', 'right'],
  bottomLeft: ['bottom', 'left'],
}

/**
 * Array of corner handles, generated by combining corners and their possible handle types.
 */
export const cornerHandles = corners.flatMap(corner =>
  cornerHandleTypes[corner].map(handle => `${corner}-${handle}`)
)

/**
 * Mapping of corner and edge to tailwind class names.
 */
export const tailwindClassMap = {
  'topLeft-top': ['top-[0.5px]', 'left-3', 'h-1', 'w-3'],
  'topLeft-left': ['top-3', 'left-[0.5px]', 'w-1', 'h-3'],
  'topRight-top': ['top-[0.5px]', 'right-0', 'h-1', 'w-3', 'left-auto'],
  'topRight-right': ['top-3', 'right-[0.5px]', 'w-1', 'h-3', 'left-auto'],
  'bottomRight-bottom': [
    'bottom-[0.5px]',
    'right-0',
    'h-1',
    'w-3',
    'top-auto',
    'left-auto',
  ],
  'bottomRight-right': [
    'bottom-[0.5px]',
    'right-[0.5px]',
    'w-1',
    'h-3',
    'top-auto',
    'left-auto',
  ],
  'bottomLeft-bottom': ['bottom-[0.5px]', 'left-3', 'h-1', 'w-3', 'top-auto'],
  'bottomLeft-left': [
    'bottom-[0.5px]',
    'left-[0.5px]',
    'w-1',
    'h-3',
    'top-auto',
  ],
}
